name: baseapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.13
  go_router: ^12.1.3 
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1 
  google_fonts: ^6.1.0 
  permission_handler: ^11.3.0 
  intl: ^0.20.2 
  package_info_plus: ^8.3.0
  http: ^1.4.0
  
# flutter_native_splash 패키지를 사용하여 스플래시 화면을 구성합니다.
# color는 스플래시 화면의 배경색을 지정하며 흰색("#FFFFFF")으로 설정되어 있습니다.
# image는 스플래시 화면에 표시할 이미지의 경로를 지정합니다. "assets/icons/splash12.png" 이미지를 사용합니다.
# android와 ios는 각각 안드로이드와 iOS 플랫폼에서 스플래시 화면을 활성화할지 여부를 나타내며 둘 다 true로 설정되어 있습니다.
# android_12 섹션은 안드로이드 12 버전에서의 스플래시 화면 설정을 정의합니다. 여기서도 배경색과 이미지는 동일하게 설정됩니다.
# fullscreen은 스플래시 화면이 전체 화면으로 표시될지 여부를 결정하며 false로 설정되어 있습니다.
# android_gravity와 ios_content_mode는 각각 안드로이드와 iOS에서 이미지의 정렬 방식을 지정하며 둘 다 중앙 정렬로 설정되어 있습니다.
# web은 웹 플랫폼에서 스플래시 화면을 사용할지 여부를 나타내며 false로 설정되어 있어 웹에서는 스플래시 화면이 비활성화됩니다.
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/splash12.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icons/splash12.png"
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

# flutter_launcher_icons 설정은 앱의 아이콘을 자동으로 생성하고 설정합니다.
# android: true는 안드로이드 플랫폼에 대해 아이콘을 생성하겠다는 의미입니다.
# ios: true는 iOS 플랫폼에 대해 아이콘을 생성하겠다는 의미입니다.
# image_path는 기본 아이콘 이미지의 경로를 지정합니다. 여기서는 "assets/icons/icon.png"로 설정되어 있습니다. image_path는 변경가능합니다.
# adaptive_icon_background는 안드로이드의 적응형 아이콘 배경색을 지정합니다. 여기서는 흰색("#FFFFFF")으로 설정되어 있습니다.
# adaptive_icon_foreground는 안드로이드의 적응형 아이콘 전경 이미지를 지정합니다. 여기서는 "assets/icons/icon.png"로 설정되어 있습니다.
# min_sdk_android는 안드로이드의 최소 SDK 버전을 지정합니다. 여기서는 21로 설정되어 있습니다.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - .env
  